name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats cards
        uses: jstrieb/github-stats@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: debarshi29

      - name: Move outputs
        run: |
          mkdir -p dist
          cp generated/overview.svg dist/github-stats-dark.svg
          cp generated/languages.svg dist/github-langs-dark.svg
          cp generated/overview.svg dist/github-stats.svg
          cp generated/languages.svg dist/github-langs.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
